name: vprofile actions

on:
  workflow_dispatch:
    inputs:
      skip_sonar:
        description: "Skip SonarQube Scan"
        required: false
        default: false
        type: boolean

env:
  AWS_REGION: us-west-2
  ECR_REPOSITORY: vprofile
  EKS_CLUSTER: vprofile-eks
  NAMESPACE: dev

jobs:
  Testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Java 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "11"
          cache: maven

      - name: Run Unit Tests
        run: mvn test

      - name: Run Checkstyle
        run: mvn checkstyle:checkstyle

      - name: SonarQube Scan
        if: ${{ !inputs.skip_sonar }}
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_URL }}
        with:
          args: >
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.sources=.
            -Dsonar.exclusions=**/target/**,src/main/resources/*.sql,src/main/resources/application.properties

  BUILD_AND_PUBLISH:
    needs: Testing
    runs-on: ubuntu-latest

    outputs:
      image-tag: ${{ github.run_number }}

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: |
          docker build -t $ECR_REPOSITORY:${{ github.run_number }} .

      - name: Tag Docker Image
        run: |
          docker tag $ECR_REPOSITORY:${{ github.run_number }} \
          ${{ secrets.REGISTRY }}/$ECR_REPOSITORY:${{ github.run_number }}

          docker tag $ECR_REPOSITORY:${{ github.run_number }} \
          ${{ secrets.REGISTRY }}/$ECR_REPOSITORY:latest

      - name: Push Docker Images
        run: |
          docker push ${{ secrets.REGISTRY }}/$ECR_REPOSITORY:${{ github.run_number }}
          docker push ${{ secrets.REGISTRY }}/$ECR_REPOSITORY:latest

  DEPLOY_TO_EKS:
    needs: BUILD_AND_PUBLISH
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Verify AWS Identity
        run: aws sts get-caller-identity

      - name: Configure kubectl
        run: |
          aws eks update-kubeconfig \
            --region ${{ env.AWS_REGION }} \
            --name ${{ env.EKS_CLUSTER }}
      - name: Who am I?
        run: aws sts get-caller-identity

      - name: Verify Cluster
        run: |
          kubectl config current-context
          kubectl get nodes

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Create or Update Image Pull Secret
        run: |
          kubectl create namespace ${{ env.NAMESPACE }} --dry-run=client -o yaml | kubectl apply -f -

          kubectl create secret docker-registry regcred \
            --docker-server=${{ secrets.REGISTRY }} \
            --docker-username=AWS \
            --docker-password="$(aws ecr get-login-password --region ${{ env.AWS_REGION }})" \
            --namespace=${{ env.NAMESPACE }} \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Setup Helm
        uses: Azure/setup-helm@v5.0.0

      - name: Check Helm Version
        run: helm version

      - name: Deploy Application
        run: |
          helm upgrade --install vprofile-stack ./helm/vprofilecharts \
            --namespace ${{ env.NAMESPACE }} \
            --create-namespace \
            --set appimage=${{ secrets.REGISTRY }}/${{ env.ECR_REPOSITORY }} \
            --set apptag=${{ github.run_number }}

      - name: Verify Deployment
        run: |
          kubectl get pods -n ${{ env.NAMESPACE }}
          kubectl get svc -n ${{ env.NAMESPACE }}
          helm list -n ${{ env.NAMESPACE }}